# Generated by Django 5.1.1 on 2025-03-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_category_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default='Статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='backend.category'),
        ),
    ]
