# Generated by Django 5.1.1 on 2025-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authorMid',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
