# Generated by Django 5.1.1 on 2025-06-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_article_authormid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('date_of_publishing', models.DateTimeField(auto_now_add=True)),
                ('likes_counter', models.IntegerField()),
            ],
        ),
    ]
