# Generated by Django 5.1.1 on 2025-06-11 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes_counter',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
